#!/usr/bin/env python
# ###################################################################
# vic.py 
# 
# main functions:
#	- sniff packet from hck.py
#	- modify process table 
# ###################################################################
from scapy.all import *
from encrypt import *
import argparse
import sys
import string
import os
from setproctitle import getproctitle, setproctitle





def main():
	title = setproctitle.getproctitle()
	print title
	raw_input("GIVE me: ")

	


if __name__ == '__main__':
	try:
		main()
	except KeyboardInterrupt:
		print("Terminate signal received. Exiting...")